name: Deploy PHP App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_PHP }}" > ~/.ssh/my_php.pem
          chmod 600 ~/.ssh/my_php.pem

      - name: Fazer deploy via SCP
        run: |
          scp -i ~/.ssh/my_php.pem -r . ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}:/var/www/html/basic-php-mvc-structure
